### ISSUE TITLE
Missing configuration button

### ISSUE THREAD

**Issue by pustovalov** [Codealike/Codealike-Atom#15]
![](https://monosnap.com/file/Xb1oCAtbrm9AU41RvKIzeQ63eJaGeB.png)

How can I configure this package?

Atom: 1.22.0

**Comment by soke1556** [comment]
If you're using other plugins for JetBrains IDE, Visual Studio Code or Eclipse, it's already configured using those editors settings.

If not: Check the status bar (Bottom left in Atom) Click in the Codealike Status and it will ask for the API Token, you can get yours from here: [https://codealike.com/Settings/Account](https://codealike.com/Settings/Account)

Let me know how it works.

**Comment by pustovalov** [comment]
1. This popup does not look like macOS popup
![](https://monosnap.com/file/oZ5rZhST9CV2NacABr9xXsu0KlwheB.png)

2. I can not paste the code from the clipboard, code must be written manually, this is bad(

It would be better to make a page with the settings for the atom instead of the popup.
